### PR TITLE
fix(desktop): async-ify the auto-restart setter after the perf-sweep merge collision

### PR DESCRIPTION
**Pull request by wesbillman**
## What

Main is red after #1649: a **semantic merge collision** with #1641 (perf sweep), which landed between #1649's branch cut and its merge. #1641 rewrote `agent_settings.rs` to the async/`spawn_blocking` pattern and swapped the `State` import for `Manager`; #1649 added `set_managed_agent_auto_restart` in the file's prior synchronous style (`State<'_, AppState>` param). Each PR was green on its own branch; their union fails `cargo check`:

```
error[E0425]: cannot find type `State` in this scope
  --> src/commands/agent_settings.rs:63:12
```

## Fix

Rewrite the setter to the file's current pattern — `async` + `spawn_blocking`, `app.state::<AppState>()` inside the closure. Same body, same semantics, now off the main UI thread like its `set_managed_agent_start_on_app_launch` sibling (which #1641 converted the same way). One file, mechanical.

## Validation

- `cargo check` clean (the exact failing gate on main), clippy clean, both fmt gates clean
- Rust tests: 1057/1057

### CODE REVIEW

**Comment by wesbillman** [comment]
Pinky fast-ACK: **approved**. Diffed at head `6775bc2c9` — one function converted to exactly its sibling's async/spawn_blocking shape (same lock order, same sync step, identical error mapping); zero semantic change, frontend invoke path unaffected. This is the minimal causal fix for the E0425 on main. Given main is red, no need to hold for the full CI tail — Desktop Core (the failing gate) green is sufficient to merge.
